### ISSUE TITLE
error in vsts on mac and windows agent

### ISSUE THREAD

**Issue by jerry2007** [kasunkv/regex-match-replace-vsts-task#1]
When I add this task to build pipeline at throw this error:

Starting: VSMC iOS Staging
******************************************************************************
==============================================================================
Task         : RegEx Match & Replace
Description  : Visual Studio Team Services Task to replace file content with a regex match
Version      : 2.0.2
Author       : Kasun Kodagoda
Help         : [More Information](https://github.com/kasunkv/regex-match-replace-vsts-task)
==============================================================================
Unhandled: Unexpected token =
******************************************************************************
Finishing: VSMC iOS Staging

**Comment by kasunkv** [comment]
@jerry2007 Can you give me more details about the input and the type of build agent you are using? It would be helpful to know the regex you are using and what content you are running the match against.

**Comment by jerry2007** [comment]
![image](https://user-images.githubusercontent.com/6752910/32137819-7e3471b4-bc27-11e7-9357-abc9bd2c406c.png)

I have build server with windows and build server with macos
On both of them it throw same error...

when i run the task with node manually it work, but from VSTS not...

**Comment by kasunkv** [comment]
Is it possible to send me the App.xaml.cs file (if there aren't any confidential stuff in the file) so i can run the same regex against it on my VSTS account. Coz the same regex seems to work, and having the file would help to pinpoint if this is a problem with the task, or the environment its running on.

**Comment by jerry2007** [comment]
`using Acr.UserDialogs;
using GalaSoft.MvvmLight.Ioc;
using GalaSoft.MvvmLight.Views;
using Microsoft.Azure.Mobile;
using Microsoft.Azure.Mobile.Analytics;
using Microsoft.Azure.Mobile.Crashes;
using Plugin.DeviceInfo;
using Plugin.Settings;
using ProfiUctenka.Helpers;
using ProfiUctenka.Interfaces;
using ProfiUctenka.Migrations;
using ProfiUctenka.Models;
using ProfiUctenka.Pages;
using ProfiUctenka.Resources;
using ProfiUctenka.Services;
using ProfiUctenka.Services.Mocks;
using ProfiUctenka.Services.S5.Dto;
using ProfiUctenka.ViewModels.Popups.Settings;
using Version.Plugin;
using Xamarin.Forms;
using Device = Xamarin.Forms.Device;

namespace ProfiUctenka
{
    public partial class App : Application
    {
        public static ViewModelLocator ViewModelLocator;
        public App()
        {        
            this.InitializeComponent();

            string id = CrossSettings.Current.GetValueOrDefault("DeviceId", string.Empty);
            if (string.IsNullOrEmpty(id))
                CrossSettings.Current.AddOrUpdateValue("DeviceId", CrossDeviceInfo.Current.GenerateAppId(true));

            var firstPage = new NavigationPage();
            ViewModelLocator = new ViewModelLocator(firstPage);

            var settings = SimpleIoc.Default.GetInstance<Settings>();

            string lastVersion = settings.Get("Lastversion", string.Empty);
            if (string.IsNullOrEmpty(lastVersion) || lastVersion != CrossVersion.Current.Version)
            {
                MigrationFactory.GetActualMigration().Migrate();
                settings.Set("Lastversion", CrossVersion.Current.Version);
            }
            
            this.MainPage = firstPage;

            if (Device.RuntimePlatform == Device.iOS || Device.RuntimePlatform == Device.Android)
            {
                var localizeService = DependencyService.Get<ILocalize>();
                var ci = localizeService.GetCurrentCultureInfo();
                Language.Culture = ci;
                localizeService.SetLocale(ci);
            }

            if (!CrossSettings.Current.GetValueOrDefault("FirstStart", true) && !CrossSettings.Current.GetValueOrDefault("NewDesignTutorialOpened", false))
            {
                CrossSettings.Current.AddOrUpdateValue("NewDesignTutorialOpened", true);
                this.MainPage.Navigation.PushModalAsync(new NewDesignTutorial());
            }
            if (CrossSettings.Current.GetValueOrDefault("FirstStart", true) || CrossSettings.Current.GetValueOrDefault("FormNotSaved", false))
            {
                this.MainPage.Navigation.PushModalAsync(new Tutorial());
            }
           
            firstPage.PushAsync(new MainPage());
        }

        public static void TestCloudInit()
        {
            MobileCenter.Enabled = false;
            SimpleIoc.Default.Register<IiDokladService, MockiDokladService>();
            SimpleIoc.Default.Register<IS5ApiService, MockS5ApiService>();
        }

        protected override void OnStart()
        {
#if DEBUG
            MobileCenter.Start(
                   "uwp=da9e5e9b-f61e-40b3-9736-53f1951f5c7a;" +
                   "android=fcea4472-8ba7-44d1-a7e9-62428a46e0de;" +
                   "ios=2f496ecd-d72b-41ac-a74f-9d14ccff32fd",
                   typeof(Analytics), typeof(Crashes));
#else
            MobileCenter.Start(
                   "uwp=9e0a3eed-db42-4ec0-917c-23ec46e5c02b;" +
                   "android=586cf03c-5737-4982-8caa-7be884005f83;" +
                   "ios=5af5cec0-885b-478b-bae7-60ea00f9a2f6",
                   typeof(Analytics), typeof(Crashes));
#endif
            // Handle when your app starts
        }

        protected override void OnSleep()
        {
            // Handle when your app sleeps
        }

        protected override void OnResume()
        {
            // Handle when your app resumes
        }
    }
}
`

**Comment by kasunkv** [comment]
@jerry2007 Thanks for sharing the file. I ran the task against this file and using the same regex and the replacement value. The task seems to work without any issues. But looking at the file, i see that the regex you applied does not return a match from this file. To return a match the `GUID` for ios in the `MobileCenter.Start()` method should have a semicolon (;) at the end. Hence no match returned. But it should not break the build. If no match is found, it simply doesn;t do any changes.  I tested the regex with [RegExr](https://regexr.com/)

Also, The build agents you are using, are the build agents that comes with VSTS? I assume the Windows Agent is, but the Mac OS agent is a private agent, am i correct?

**Comment by jerry2007** [comment]
ok, but the error which it raising look like it never start regex...
It look like it wont start replacement...

Both of that agents are private...

**Comment by kasunkv** [comment]
Then its most likely an issue with the agents itself. Does the agents have node and npm installed? Also, if you are presented with a detailed error message, pls post it here as well.

**Comment by jerry2007** [comment]
yes it look like the problem is with private agent...
But after 12 hours I dont know where...
On hosted agent it work on private not...

I have Node 8.8.1
npm 5.4.2

I found more log info...

C:\Users\adeploy>C:\agent\externals\node\bin\node.exe "C:\agent\_work\_tasks\RegExMatchReplace_86e3367d-c1d2-40a3-ab67-abd1924ce49f\2.0.2\regexMatchReplace.js"
##vso[task.debug]agent.TempDirectory=undefined
##vso[task.debug]agent.workFolder=undefined
##vso[task.debug]loading inputs and endpoints
##vso[task.debug]loaded 0
##vso[task.debug]Agent.ProxyUrl=undefined
##vso[task.debug]Agent.CAInfo=undefined
##vso[task.debug]Agent.ClientCert=undefined
##vso[task.debug]task result: Failed
##vso[task.issue type=error;]Unhandled: Unexpected token =
##vso[task.complete result=Failed;]Unhandled: Unexpected token =

here is the error... but i dont why...

**Comment by kasunkv** [comment]
I will try setting up a private agent and using the task on that private agent to see if i can reproduce this issue.

**Comment by jerry2007** [comment]
I found out that problem...
when i edit helper.js and regExMatch.js like that I remove default parameters values...

`static WriteConsoleInformation(message, param, debug = false) {`
to
`static WriteConsoleInformation(message, param, debug) {`

and

`static MatchAndReplace(content, expression, valueToReplace, global = true, ignoreCase = false, multiLine = false) {
`

to

`static MatchAndReplace(content, expression, valueToReplace, global, ignoreCase, multiLine) {`

after this edit everything has started to work...

**Comment by kasunkv** [comment]
@jerry2007 So its an issue with the task after all. Thank you for figuring it out. If you like please do create a PR with the fix. Or let me know here, i will make the change and publish the new update to the marketplace.

**Comment by kasunkv** [comment]
@jerry2007 I will create the fix for this and update the task now. So you can start using it immediately.

**Comment by jerry2007** [comment]
great thank you...

**Comment by kasunkv** [comment]
@jerry2007 The version 2.0.3 with the fix for this issue is now published. Your issue should now be solved. Please test and let me know here so i can close this issue. Once again thank you for using  the task and for the help figuring out the issue.

**Comment by jerry2007** [comment]
@kasunkv yes it work... thank you...
